// SPDX-FileCopyrightText: 2026 Lido <info@lido.fi>
// SPDX-License-Identifier: GPL-3.0

pragma solidity 0.8.33;

import { Math } from "@openzeppelin/contracts/utils/math/Math.sol";

import { IBaseModule, NodeOperator, WithdrawnValidatorInfo } from "../interfaces/IBaseModule.sol";
import { ExitPenaltyInfo } from "../interfaces/IExitPenalties.sol";
import { ModuleLinearStorage } from "../abstract/ModuleLinearStorage.sol";

import { KeyPointerLib } from "./KeyPointerLib.sol";
import { SigningKeys } from "./SigningKeys.sol";
import { ValidatorBalanceLimits } from "./ValidatorBalanceLimits.sol";

/// @dev External deployment-linked library that processes withdrawn validators.
library WithdrawnValidatorLib {
    /// @dev Module-specific inputs for penalty calculation. The multiplier scales penalties expressed at the base
    ///      validator balance; the final penalty amount is added without further scaling.
    struct PenaltyBasis {
        uint256 penaltyMultiplier;
        uint256 penaltyAmount;
    }

    uint256 public constant PENALTY_QUOTIENT = 1 ether;
    /// @dev Acts as the denominator to calculate the scaled penalty.
    uint256 public constant PENALTY_SCALE = ValidatorBalanceLimits.MIN_ACTIVATION_BALANCE / PENALTY_QUOTIENT;

    /// @dev Processes a terminal validator report.
    /// @param penaltyBasis Module-specific multiplier and final penalty amount.
    /// @param info Validator withdrawal report to process.
    /// @param slashed Whether the report was generated by the automatic slashing flow.
    /// @param $ Base module storage.
    /// @return trackedBalanceDecrease Allocated balance to remove for the key.
    function processValidator(
        PenaltyBasis calldata penaltyBasis,
        WithdrawnValidatorInfo calldata info,
        bool slashed,
        ModuleLinearStorage.BaseModuleStorage storage $
    ) external returns (uint256 trackedBalanceDecrease) {
        if (info.nodeOperatorId >= $.nodeOperatorsCount) revert IBaseModule.NodeOperatorDoesNotExist();

        uint256 pointer = KeyPointerLib.keyPointer(info.nodeOperatorId, info.keyIndex);
        if ($.isValidatorWithdrawn[pointer]) revert IBaseModule.ValidatorAlreadyWithdrawn();
        // A slashing recorded before the upgrade must also be settled through the automatic slashing flow.
        if ($.isValidatorSlashed[pointer] && !slashed) revert IBaseModule.SlashingPenaltyIsNotApplicable();
        if (!$.isValidatorSlashed[pointer] && slashed) revert IBaseModule.SlashingPenaltyIsNotApplicable();

        _processValidator($.nodeOperators[info.nodeOperatorId], info, penaltyBasis);

        $.isValidatorWithdrawn[pointer] = true;
        return $.keyAllocatedBalance[pointer];
    }

    function scalePenalty(uint256 penalty, uint256 balance) internal pure returns (uint256) {
        balance = _clamp(
            balance,
            ValidatorBalanceLimits.MIN_ACTIVATION_BALANCE,
            ValidatorBalanceLimits.MAX_EFFECTIVE_BALANCE
        );
        uint256 multiplier = _getPenaltyMultiplier(balance);
        return _scalePenaltyByMultiplier(penalty, multiplier);
    }

    /// @dev Acts as the numerator to calculate the scaled penalty.
    /// @dev Expects the `balance` value between MIN_ACTIVATION_BALANCE and MAX_EFFECTIVE_BALANCE.
    function _getPenaltyMultiplier(uint256 balance) internal pure returns (uint256 penaltyMultiplier) {
        penaltyMultiplier = balance / PENALTY_QUOTIENT;
    }

    function _scalePenaltyByMultiplier(uint256 penalty, uint256 multiplier) internal pure returns (uint256) {
        return (penalty * multiplier) / PENALTY_SCALE;
    }

    function _clamp(uint256 v, uint256 min, uint256 max) internal pure returns (uint256) {
        return Math.min(Math.max(v, min), max);
    }

    function _processValidator(
        NodeOperator storage no,
        WithdrawnValidatorInfo calldata info,
        PenaltyBasis calldata penaltyBasis
    ) private {
        if (info.keyIndex >= no.totalDepositedKeys) revert IBaseModule.SigningKeysInvalidOffset();

        unchecked {
            ++no.totalWithdrawnKeys;
        }

        bytes memory pubkey = SigningKeys.loadKeys(info.nodeOperatorId, info.keyIndex, 1);
        ExitPenaltyInfo memory penaltyInfo = IBaseModule(address(this)).EXIT_PENALTIES().getExitPenaltyInfo(
            info.nodeOperatorId,
            pubkey
        );
        uint256 penaltySum;

        if (penaltyInfo.strikesPenalty.isValue) {
            // NOTE: This might overflow for a recorded penalty greater than about 2^245.
            penaltySum = _scalePenaltyByMultiplier(penaltyInfo.strikesPenalty.value, penaltyBasis.penaltyMultiplier);
        }

        penaltySum += penaltyBasis.penaltyAmount;

        if (penaltySum != 0) IBaseModule(address(this)).ACCOUNTING().penalize(info.nodeOperatorId, penaltySum);

        emit IBaseModule.ValidatorWithdrawn({
            nodeOperatorId: info.nodeOperatorId,
            keyIndex: info.keyIndex,
            pubkey: pubkey
        });
    }
}
