// SPDX-FileCopyrightText: 2026 Lido <info@lido.fi>
// SPDX-License-Identifier: GPL-3.0

pragma solidity 0.8.33;

import { Test } from "forge-std/Test.sol";

import { DeployParams } from "script/csm/DeployBase.s.sol";
import { DeployCSM0x02Params } from "script/csm0x02/DeployCSM0x02Base.s.sol";
import { CuratedDeployParams, CuratedGateConfig } from "script/curated/DeployBase.s.sol";
import { TwoPhaseFrameConfigUpdateParams } from "script/DeployTwoPhaseFrameConfigUpdate.s.sol";
import { JsonBindings } from "script/utils/JsonBindings.sol";
import { pack } from "src/lib/GIndex.sol";

/// @dev The deployment params are stored in the artifacts as JSON objects, (de)serialized with the bindings
///      generated by `forge bind-json`. The round trips check that the params types are supported by the
///      cheatcodes, `just bind-json-check` is what keeps the bindings in sync with the structs.
contract DeployParamsJsonTest is Test {
    function test_deployParams() public {
        DeployParams memory params;
        params.aragonAgent = address(0xA11CE);
        params.gIFirstWithdrawal = pack(0xe1c004, 4);
        params.moduleType = keccak256("community-onchain-v1");
        params.topUpQueueLimit = 42;
        params.oracleMembers = new address[](1);
        params.oracleMembers[0] = address(0xBEEF);
        params.defaultBondCurve = new uint256[2][](1);
        params.defaultBondCurve[0] = [uint256(1), 2 ether];
        params.extraBondCurves = new uint256[2][][](1);
        params.extraBondCurves[0] = new uint256[2][](1);
        params.extraBondCurves[0][0] = [uint256(3), 4 ether];
        params.identifiedCommunityStakersGateName = "Identified Community Stakers Gate";

        string memory json = JsonBindings.serialize(params, "csm", "DeployParams");
        DeployParams memory back = JsonBindings.deserializeDeployParams(json, ".DeployParams");

        assertEq(keccak256(abi.encode(back)), keccak256(abi.encode(params)));
    }

    function test_deployCSM0x02Params() public {
        DeployCSM0x02Params memory params;
        params.aragonAgent = address(0xA11CE);
        params.gIFirstWithdrawal = pack(0xe1c004, 4);
        params.moduleType = keccak256("community-onchain-v2");
        params.topUpQueueLimit = 42;
        params.oracleMembers = new address[](1);
        params.oracleMembers[0] = address(0xBEEF);
        params.defaultBondCurve = new uint256[2][](1);
        params.defaultBondCurve[0] = [uint256(1), 2 ether];
        params.extraBondCurves = new uint256[2][][](1);
        params.extraBondCurves[0] = new uint256[2][](1);
        params.extraBondCurves[0][0] = [uint256(3), 4 ether];

        string memory json = JsonBindings.serialize(params, "csm0x02", "DeployParams");
        DeployCSM0x02Params memory back = JsonBindings.deserializeDeployCSM0x02Params(json, ".DeployParams");

        assertEq(keccak256(abi.encode(back)), keccak256(abi.encode(params)));
    }

    function test_curatedDeployParams() public {
        CuratedDeployParams memory params;
        params.aragonAgent = address(0xA11CE);
        params.gIFirstWithdrawal = pack(0xe1c004, 4);
        params.moduleType = keccak256("curated-onchain-v2");
        params.oracleMembers = new address[](1);
        params.oracleMembers[0] = address(0xBEEF);
        params.defaultBondCurve = new uint256[2][](1);
        params.defaultBondCurve[0] = [uint256(1), 2 ether];
        params.curatedGates = new CuratedGateConfig[](1);
        params.curatedGates[0].name = "Curated Gate";
        params.curatedGates[0].bondCurve = new uint256[2][](1);
        params.curatedGates[0].bondCurve[0] = [uint256(5), 6 ether];
        params.curatedGates[0].params.keysLimit.value = 7;
        params.curatedGates[0].params.keysLimit.isValue = true;

        string memory json = JsonBindings.serialize(params, "curated", "CuratedDeployParams");
        CuratedDeployParams memory back = JsonBindings.deserializeCuratedDeployParams(json, ".CuratedDeployParams");

        assertEq(keccak256(abi.encode(back)), keccak256(abi.encode(params)));
    }

    function test_twoPhaseFrameConfigUpdateParams() public {
        TwoPhaseFrameConfigUpdateParams memory params = TwoPhaseFrameConfigUpdateParams({
            reportsToProcessBeforeOffsetPhase: 1,
            reportsToProcessBeforeRestorePhase: 2,
            offsetPhaseEpochsPerFrame: 3,
            restorePhaseFastLaneLengthSlots: 4
        });

        string memory json = JsonBindings.serialize(params, "utils", "TwoPhaseFrameConfigUpdateParams");
        TwoPhaseFrameConfigUpdateParams memory back = JsonBindings.deserializeTwoPhaseFrameConfigUpdateParams(
            json,
            ".TwoPhaseFrameConfigUpdateParams"
        );

        assertEq(keccak256(abi.encode(back)), keccak256(abi.encode(params)));
    }
}
